### PR TITLE
entrypoint.sh: Check SIMULATION var for launch static transform only

### PR DESCRIPTION
**Pull request by jnippula**
SIMULATION flag for sim launch

### CODE REVIEW

**Review by mehmetkillioglu — COMMENTED** [review]
Not sure if this is effective. The launch file does not take LaunchArgument like in the other nodes.

https://github.com/tiiuae/rplidar_ros2/blob/new_ros2/launch/static_tf_launch.py

Example launch with use_sim_time param input.
https://github.com/tiiuae/fog_bumper/blob/master/launch/bumper_launch.py

**Comment by mehmetkillioglu** [comment]
Also, it might be not required to pass use_sim_time to static_transform_publisher at all.

**Comment by jnippula** [comment]
> Also, it might be not required to pass use_sim_time to static_transform_publisher at all.

That is right. The timestamp is not relevant for static_tf messages as they are not connected to any specific moment. It is kind of timeless information.

**Review by mehmetkillioglu — APPROVED** [review]
I guess this is better than handling the env value inside the launch file.

**Review by joonas-fi — APPROVED** [review]
Looks good, but before merging see question in https://github.com/tiiuae/navigation/pull/23

**Pull request merged**
