### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by spurnvoj**
Only small changes, that don't impact functionality.

### CODE REVIEW

**Comment by spurnvoj** [comment]
@jnippula or @maseabunikie I don't want to merge it without your confirmation.

**Comment by maseabunikie** [comment]
We were planning to merge these changes after we have have validated the latest changes waiting in PRs for navigation and control_interface.
But these changes should work in Foxy also, isn't it? Then I guess it would be merged already.

**Comment by spurnvoj** [comment]
Yes, I just tested it on foxy and it works there too :)

**Comment by maseabunikie** [comment]
Then it should be ok to merge this change.

**Review by maseabunikie — APPROVED** [review]

**Pull request merged**
